### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by Vasolix** [yuzu-emu/yuzu-multiplayer-dedicated#5]
[51934.832357] WebService <Error> web_service/web_backend.cpp:GenericRequest:114: POST to https://api.yuzu-emu.org/lobby/*************************************** returned null (httplib Error: Failed to read connection)

**Comment by liushuyu** [comment]
It should be fixed now. Can you try again with the latest image?

**Comment by Vasolix** [comment]
I no longer have this error I believe, not yet tested for more than a day but I also have another error

`[1248.005828] Network <Error> network/room.cpp:HandleLdnPacket:916: Attempting to send to unknown IP address: 192.168.231.203
[1249.439058] Network <Error> network/room.cpp:HandleLdnPacket:916: Attempting to send to unknown IP address: 192.168.231.203
[1257.451482] Network <Error> network/room.cpp:HandleLdnPacket:916: Attempting to send to unknown IP address: 192.168.231.203
[1257.843561] Network <Error> network/room.cpp:HandleLdnPacket:916: Attempting to send to unknown IP address: 192.168.231.203
[1270.852809] Network <Error> network/room.cpp:HandleLdnPacket:916: Attempting to send to unknown IP address: 192.168.231.203`

**Comment by liushuyu** [comment]
> I no longer have this error I believe, not yet tested for more than a day but I also have another error
> 
> `[1248.005828] Network <Error> network/room.cpp:HandleLdnPacket:916: Attempting to send to unknown IP address: 192.168.231.203 `

I think this is probably due to someone in your room dropped out mid-session.

**Comment by Vasolix** [comment]
![image](https://github.com/yuzu-emu/yuzu-multiplayer-dedicated/assets/38722359/7a548006-235e-4b03-8228-6231d9e29e55)
the error came back

**Comment by liushuyu** [comment]
> [1846.354973] WebService web_service/web_backend.cpp:GenericRequest:120: POST to https://api.yuzu-emu.org/lobby/150a72e4-47d8-4f5d-9d36-633311515695 returned error status code: 401
> 
> [2221.225157] WebService web_service/web_backend.cpp:GenericRequest:114: POST to https://api.yuzu-emu.org/lobby/150a72e4-47d8-4f5d-9d36-633311515695 returned null (httplib Error: Failed to read connection) the error came back

Hmm okay. I will take a look.
